### ISSUE TITLE
fail to build: AttributeError: 'bool' object has no attribute 'format'

### ISSUE THREAD

**Issue by come-maiz** [elopio/tangamandapio#1]
Master branch is failing to build:
https://travis-ci.org/elopio/tangamandapio/builds/85440599

TaskError - taskid:render_tags:output/es/categories/snappy.xml

PythonAction Error

Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/doit/action.py", line 383, in execute

```
returned_value = self.py_callable(*self.args, **kwargs)
```

  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/nikola/nikola.py", line 1312, in generic_rss_renderer

```
feedFormat="rss")
```

  File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/nikola/utils.py", line 361, in format

```
self.values[l] = self.values[l].format(*args, **kwargs)
```

AttributeError: 'bool' object has no attribute 'format'

**Comment by come-maiz** [comment]
upstream: getnikola/nikola#2140
